INSERT INTO PUBLIC.TB_EMPRESA
( CNPJ, DATA_ATUALIZACAO, DATA_CRIACAO, RAZAO_SOCIAL)
VALUES( '81279675645342', now(), now(), 'Beto IT');

INSERT INTO PUBLIC.TB_FUNCIONARIO
( CPF, DATA_ATUALIZACAO, DATA_CRIACAO, EMAIL, NOME, PERFIL, QTD_HORAS_ALMOCO, QTD_HORAS_TRABALHO_DIA, SENHA, VALOR_HORA, EMPRESA_ID)
VALUES( '03406322912', now(), now(), 'beto@email.com', 'ADMIN', 'ROLE_ADMIN', NULL, NULL, '$2a$10$17Oy79JsCf9d1uTXlibIxOKBZwlRWv/QzEeaCeXJ/Q0qwFiaqqHwK', NULL, (SELECT ID FROM public.TB_EMPRESA WHERE CNPJ = '81279675645342'));
